# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bts.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbts.proto\"\r\n\x0bVersionArgs\"\x0c\n\nRoutesArgs\"=\n\x0cVersionReply\x12\x16\n\x0e\x65xabgp_version\x18\x01 \x01(\t\x12\x15\n\rflask_version\x18\x02 \x01(\t\"i\n\tRouteItem\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x10\n\x08neighbor\x18\x02 \x01(\t\x12\x0f\n\x07nexthop\x18\x03 \x01(\t\x12\x0e\n\x06pathid\x18\x04 \x01(\t\x12\x0b\n\x03\x61\x66i\x18\x05 \x01(\t\x12\x0c\n\x04safi\x18\x06 \x01(\t\"8\n\x0bRoutesReply\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\x1a\n\x06routes\x18\x02 \x03(\x0b\x32\n.RouteItem\"t\n\x0c\x41nnounceArgs\x12\x10\n\x06prefix\x18\x01 \x01(\tH\x00\x12\x11\n\x07nexthop\x18\x02 \x01(\tH\x01\x12\x10\n\x08neighbor\x18\x03 \x01(\t\x12\x0e\n\x06pathid\x18\x04 \x01(\rB\r\n\x0bprefix_reqtB\x0e\n\x0cnexthop_reqt\"B\n\rAnnounceReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x03(\t\"R\n\x0cWithdrawArgs\x12\x10\n\x06prefix\x18\x01 \x01(\tH\x00\x12\x10\n\x08neighbor\x18\x02 \x01(\t\x12\x0f\n\x07path_id\x18\x03 \x01(\rB\r\n\x0bprefix_reqt\"B\n\rWithdrawReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x03(\t\",\n\x07RawArgs\x12\x11\n\x07\x63ommand\x18\x01 \x01(\tH\x00\x42\x0e\n\x0c\x63ommand_reqt\"=\n\x08RawReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x03(\t2\xdd\x01\n\x03\x42TS\x12+\n\nVersionRPC\x12\x0c.VersionArgs\x1a\r.VersionReply\"\x00\x12(\n\tRoutesRPC\x12\x0b.RoutesArgs\x1a\x0c.RoutesReply\"\x00\x12.\n\x0b\x41nnounceRPC\x12\r.AnnounceArgs\x1a\x0e.AnnounceReply\"\x00\x12.\n\x0bWithdrawRPC\x12\r.WithdrawArgs\x1a\x0e.WithdrawReply\"\x00\x12\x1f\n\x06RawRPC\x12\x08.RawArgs\x1a\t.RawReply\"\x00\x62\x06proto3'
)




_VERSIONARGS = _descriptor.Descriptor(
  name='VersionArgs',
  full_name='VersionArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=26,
)


_ROUTESARGS = _descriptor.Descriptor(
  name='RoutesArgs',
  full_name='RoutesArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=40,
)


_VERSIONREPLY = _descriptor.Descriptor(
  name='VersionReply',
  full_name='VersionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exabgp_version', full_name='VersionReply.exabgp_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flask_version', full_name='VersionReply.flask_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=103,
)


_ROUTEITEM = _descriptor.Descriptor(
  name='RouteItem',
  full_name='RouteItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='RouteItem.prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='RouteItem.neighbor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nexthop', full_name='RouteItem.nexthop', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pathid', full_name='RouteItem.pathid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='afi', full_name='RouteItem.afi', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='safi', full_name='RouteItem.safi', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=210,
)


_ROUTESREPLY = _descriptor.Descriptor(
  name='RoutesReply',
  full_name='RoutesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='RoutesReply.count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routes', full_name='RoutesReply.routes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=268,
)


_ANNOUNCEARGS = _descriptor.Descriptor(
  name='AnnounceArgs',
  full_name='AnnounceArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='AnnounceArgs.prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nexthop', full_name='AnnounceArgs.nexthop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='AnnounceArgs.neighbor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pathid', full_name='AnnounceArgs.pathid', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='prefix_reqt', full_name='AnnounceArgs.prefix_reqt',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='nexthop_reqt', full_name='AnnounceArgs.nexthop_reqt',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=270,
  serialized_end=386,
)


_ANNOUNCEREPLY = _descriptor.Descriptor(
  name='AnnounceReply',
  full_name='AnnounceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='AnnounceReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='AnnounceReply.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='AnnounceReply.response', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=454,
)


_WITHDRAWARGS = _descriptor.Descriptor(
  name='WithdrawArgs',
  full_name='WithdrawArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='WithdrawArgs.prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='WithdrawArgs.neighbor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path_id', full_name='WithdrawArgs.path_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='prefix_reqt', full_name='WithdrawArgs.prefix_reqt',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=456,
  serialized_end=538,
)


_WITHDRAWREPLY = _descriptor.Descriptor(
  name='WithdrawReply',
  full_name='WithdrawReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='WithdrawReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='WithdrawReply.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='WithdrawReply.response', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=606,
)


_RAWARGS = _descriptor.Descriptor(
  name='RawArgs',
  full_name='RawArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='RawArgs.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command_reqt', full_name='RawArgs.command_reqt',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=608,
  serialized_end=652,
)


_RAWREPLY = _descriptor.Descriptor(
  name='RawReply',
  full_name='RawReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RawReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='RawReply.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='RawReply.response', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=715,
)

_ROUTESREPLY.fields_by_name['routes'].message_type = _ROUTEITEM
_ANNOUNCEARGS.oneofs_by_name['prefix_reqt'].fields.append(
  _ANNOUNCEARGS.fields_by_name['prefix'])
_ANNOUNCEARGS.fields_by_name['prefix'].containing_oneof = _ANNOUNCEARGS.oneofs_by_name['prefix_reqt']
_ANNOUNCEARGS.oneofs_by_name['nexthop_reqt'].fields.append(
  _ANNOUNCEARGS.fields_by_name['nexthop'])
_ANNOUNCEARGS.fields_by_name['nexthop'].containing_oneof = _ANNOUNCEARGS.oneofs_by_name['nexthop_reqt']
_WITHDRAWARGS.oneofs_by_name['prefix_reqt'].fields.append(
  _WITHDRAWARGS.fields_by_name['prefix'])
_WITHDRAWARGS.fields_by_name['prefix'].containing_oneof = _WITHDRAWARGS.oneofs_by_name['prefix_reqt']
_RAWARGS.oneofs_by_name['command_reqt'].fields.append(
  _RAWARGS.fields_by_name['command'])
_RAWARGS.fields_by_name['command'].containing_oneof = _RAWARGS.oneofs_by_name['command_reqt']
DESCRIPTOR.message_types_by_name['VersionArgs'] = _VERSIONARGS
DESCRIPTOR.message_types_by_name['RoutesArgs'] = _ROUTESARGS
DESCRIPTOR.message_types_by_name['VersionReply'] = _VERSIONREPLY
DESCRIPTOR.message_types_by_name['RouteItem'] = _ROUTEITEM
DESCRIPTOR.message_types_by_name['RoutesReply'] = _ROUTESREPLY
DESCRIPTOR.message_types_by_name['AnnounceArgs'] = _ANNOUNCEARGS
DESCRIPTOR.message_types_by_name['AnnounceReply'] = _ANNOUNCEREPLY
DESCRIPTOR.message_types_by_name['WithdrawArgs'] = _WITHDRAWARGS
DESCRIPTOR.message_types_by_name['WithdrawReply'] = _WITHDRAWREPLY
DESCRIPTOR.message_types_by_name['RawArgs'] = _RAWARGS
DESCRIPTOR.message_types_by_name['RawReply'] = _RAWREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionArgs = _reflection.GeneratedProtocolMessageType('VersionArgs', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONARGS,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:VersionArgs)
  })
_sym_db.RegisterMessage(VersionArgs)

RoutesArgs = _reflection.GeneratedProtocolMessageType('RoutesArgs', (_message.Message,), {
  'DESCRIPTOR' : _ROUTESARGS,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:RoutesArgs)
  })
_sym_db.RegisterMessage(RoutesArgs)

VersionReply = _reflection.GeneratedProtocolMessageType('VersionReply', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREPLY,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:VersionReply)
  })
_sym_db.RegisterMessage(VersionReply)

RouteItem = _reflection.GeneratedProtocolMessageType('RouteItem', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEITEM,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:RouteItem)
  })
_sym_db.RegisterMessage(RouteItem)

RoutesReply = _reflection.GeneratedProtocolMessageType('RoutesReply', (_message.Message,), {
  'DESCRIPTOR' : _ROUTESREPLY,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:RoutesReply)
  })
_sym_db.RegisterMessage(RoutesReply)

AnnounceArgs = _reflection.GeneratedProtocolMessageType('AnnounceArgs', (_message.Message,), {
  'DESCRIPTOR' : _ANNOUNCEARGS,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:AnnounceArgs)
  })
_sym_db.RegisterMessage(AnnounceArgs)

AnnounceReply = _reflection.GeneratedProtocolMessageType('AnnounceReply', (_message.Message,), {
  'DESCRIPTOR' : _ANNOUNCEREPLY,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:AnnounceReply)
  })
_sym_db.RegisterMessage(AnnounceReply)

WithdrawArgs = _reflection.GeneratedProtocolMessageType('WithdrawArgs', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWARGS,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:WithdrawArgs)
  })
_sym_db.RegisterMessage(WithdrawArgs)

WithdrawReply = _reflection.GeneratedProtocolMessageType('WithdrawReply', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWREPLY,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:WithdrawReply)
  })
_sym_db.RegisterMessage(WithdrawReply)

RawArgs = _reflection.GeneratedProtocolMessageType('RawArgs', (_message.Message,), {
  'DESCRIPTOR' : _RAWARGS,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:RawArgs)
  })
_sym_db.RegisterMessage(RawArgs)

RawReply = _reflection.GeneratedProtocolMessageType('RawReply', (_message.Message,), {
  'DESCRIPTOR' : _RAWREPLY,
  '__module__' : 'bts_pb2'
  # @@protoc_insertion_point(class_scope:RawReply)
  })
_sym_db.RegisterMessage(RawReply)



_BTS = _descriptor.ServiceDescriptor(
  name='BTS',
  full_name='BTS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=718,
  serialized_end=939,
  methods=[
  _descriptor.MethodDescriptor(
    name='VersionRPC',
    full_name='BTS.VersionRPC',
    index=0,
    containing_service=None,
    input_type=_VERSIONARGS,
    output_type=_VERSIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RoutesRPC',
    full_name='BTS.RoutesRPC',
    index=1,
    containing_service=None,
    input_type=_ROUTESARGS,
    output_type=_ROUTESREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnnounceRPC',
    full_name='BTS.AnnounceRPC',
    index=2,
    containing_service=None,
    input_type=_ANNOUNCEARGS,
    output_type=_ANNOUNCEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WithdrawRPC',
    full_name='BTS.WithdrawRPC',
    index=3,
    containing_service=None,
    input_type=_WITHDRAWARGS,
    output_type=_WITHDRAWREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RawRPC',
    full_name='BTS.RawRPC',
    index=4,
    containing_service=None,
    input_type=_RAWARGS,
    output_type=_RAWREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BTS)

DESCRIPTOR.services_by_name['BTS'] = _BTS

# @@protoc_insertion_point(module_scope)
