---
language: "python"
python:
  - "3.7"

install:
  - "sudo pip install -r exabgp/requirements.txt"
  - "sudo exabgp/make_pipes.sh"

before_script:
  - "sudo pylint exabgp/*.py"
  - "sudo black --line-length 80 --check exabgp/*.py"
  - "sudo exabgp exabgp/conf.txt --test"

script:
  - "sudo exabgp exabgp/conf.txt &"
  - "sudo pytest --verbose exabgp/test_api.py"
