---
language: "python"
python:
  - "3.7"

install:
  - "pip install -r exabgp/requirements.txt"
  - "sudo exabgp/make_pipes.sh"

before_script:
  - "pylint exabgp/*.py"
  - "black --line-length 80 --check exabgp/*.py"
  - "exabgp exabgp/conf.txt --test"
  - "exabgp exabgp/ci.txt --test"

script:
  - "env exabgp.tcp.bind=127.0.0.1 exabgp.tcp.port=5001 exabgp exabgp/ci.txt &"
  - "pytest --verbose exabgp/test_api.py"
...
