---
language: "python"
python:
  - "3.7"

install:
  - "pip install -r exabgp/requirements.txt"

before_script:
  - "pylint exabgp/*.py"
  - "black --line-length 80 --check exabgp/*.py"
  - "exabgp exabgp/conf.ini --test"

script:
  - "exabgp exabgp/conf.ini &"
  - "pytest --verbose exabgp/test_api.py"
