---
jobs:
  include:
    - name: "Flask HTTP API"
      language: "python"
      python: ["3.7.3"]
      install: ["./install.sh flask"]
      before_script: ["./before_script.sh flask"]
      script: ["./script.sh flask"]

    - name: "gRPC API"
      language: "python"
      python: ["3.7.3"]
      install:
        - "./install.sh grpc"
        - "./grpc/compile.sh grpc"
      before_script: ["./before_script.sh grpc"]
      script: ["./script.sh grpc"]

    - name: "FastAPI REST API"
      language: "python"
      python: ["3.7.3"]
      install: ["./install.sh fastapi"]
      before_script: ["./before_script.sh fastapi"]
      script: ["./script.sh fastapi"]
...
