---
jobs:
  include:

    # Test Flask HTTP API
    - language: "python"
      python:
        - "3.7"

      install:
        - "pip install -r flask/requirements.txt"
        - "sudo ./make_pipes.sh"

      before_script:
        - "pylint flask/*.py"
        - "black --line-length 82 --check flask/*.py"
        - 'sed --in-place "s:BUILD_DIR:$TRAVIS_BUILD_DIR:" flask/ci.txt'
        - "head --lines=5 flask/ci.txt"
        - "exabgp flask/ci.txt --validate"
        - "exabgp flask/conf.txt --validate"

      script:
        - >-
          env exabgp.tcp.bind=127.0.0.1
          exabgp.tcp.port=5001
          exabgp flask/ci.txt &
        - "pytest --verbose flask/test_api.py"

    # Test gRPC API
    - language: "python"
      python:
        - "3.7"

      install:
        - "pip install -r grpc/requirements.txt"
        - "sudo ./make_pipes.sh"
        - "./grpc/compile.sh grpc"

      before_script:
        - "pylint grpc/server.py grpc/test_api.py"
        - "black --line-length 82 --check grpc/server.py grpc/test_api.py"
        - 'sed --in-place "s:BUILD_DIR:$TRAVIS_BUILD_DIR:" grpc/ci.txt'
        - "head --lines=5 grpc/ci.txt"
        - "exabgp grpc/ci.txt --validate"
        - "exabgp grpc/conf.txt --validate"

      script:
        - >-
          env exabgp.tcp.bind=127.0.0.1
          exabgp.tcp.port=5001
          exabgp grpc/ci.txt &
        - "pytest --verbose grpc/test_api.py"

    # Test FastAPI REST API
    - language: "python"
      python:
        - "3.7"

      install:
        - "pip install -r fastapi/requirements.txt"
        - "sudo ./make_pipes.sh"

      before_script:
        - "pylint fastapi/*.py"
        - "black --line-length 82 --check fastapi/*.py"
        - 'sed --in-place "s:BUILD_DIR:$TRAVIS_BUILD_DIR:" fastapi/ci.txt'
        - "head --lines=5 fastapi/ci.txt"
        - "exabgp flask/ci.txt --validate"
        - "exabgp flask/conf.txt --validate"

      script:
        - >-
          env exabgp.tcp.bind=127.0.0.1
          exabgp.tcp.port=5001
          exabgp flask/ci.txt &
        - "true"
        # - "pytest --verbose fastapi/test_api.py"
...
